repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pre-commit
    rev: v4.2.0
    hooks:
      - id: validate_manifest

  - repo: local
    hooks:
      - id: fmt
        name: cargo-fmt
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
        pass_filenames: true
